README.md, source/conventions.rst, source/index.rst
=> Issue23 conventions

source/index.rst
Need to add the northern light use case to the index
=> Added northern light case to index

source/architecture.rst, source/container.puml, source/context.puml
Last updates after discussions with Håvard and Massimo.
=> Finalize architecture draft

source/use_cases.rst
#2 Fixed a typo in the use_cases.rst
=> hotfix2 typo in use_cases.rst

source/definition_of_done.rst
=> #66: updated DoD according to discussion at standup meeting 30/1

.gitignore, Vagrantfile, source/devel_environ.rst, source/index.rst, source/write_docs.rst
Started documenting development environment.
Added a Vagrantfile compiling documentation without installing things on own OS.
Related to:
* #62
=> Issue62 vagrant doc

source/frost.rst
#70 Some information as requested in #58
=> #70 added some information as requested in #58

source/dm_recipes.rst, source/index.rst
#72 
This should be merged to have the structure in place, although we'll need to add more content.
=> Issue72 implement mock

source/architecture.rst
=> #78: three DOI alternatives

source/devel_environ.rst
Added how to use `vagrant-resize` plugin to resize VM disk.
=> #75 Added information how to resize a VM disk.

source/devel_docker_ci.rst, source/index.rst
=> first draft of ci documentation #161

source/dm_recipes.rst, source/doi_at_met.rst, source/doi_background.rst, source/doi_how_to.rst, source/doi_howto.rst
I've added some documentation for DOI. Some parts are still related now to ADC, but can be change later on if needed. I'll be happy to review and integrate any of your comments/requests or suggestions.
=> Doi documentation

source/fair_documentation.rst, source/index.rst
A brief into to FAIR. More links can be added on the way.
=> Fair documentation

source/definition_of_done.rst, source/general_conventions.rst
=> Issue169 contribution agreement

source/index.rst
=> #176: Make 'Data Management Recipes' a separate chapter

source/devel_environ.rst, source/dm_recipes.rst
Issue #213. This contains updates to the docs in relation to https://github.com/metno/S-ENDA-csw-catalog-service/pull/8.
=> #213: updated documentation

source/S-ENDA-metadata-service-context-diagram.puml, source/devel_environ.rst, source/puml/development_workflow.puml
#224 This should be ok for a start...
=> #224: first draft of workflow diagram

source/metadata_management_heritage.rst, source/nina_metadata.rst
Draft of NINA metadata info. To be checked
=> Issue219 nina metadata info

source/dm_recipes.rst
Added a small description how to add and make netcdf-cf data available on thredds
=> Added netcdf to thredds description

source/architecture.rst, source/puml/architecture/S-ENDA-context-diagram.puml, source/puml/architecture/S-ENDA-data-distribution-container-diagram.puml, source/puml/architecture/S-ENDA-discovery-metadata-service-container-diagram.puml
Closes #281. Is it detailed enough? Do we miss anything?
=> Issue281 mapserver and monitoring

Vagrantfile, source/architecture.rst, source/puml/architecture/S-ENDA-discovery-metadata-service-container-diagram.puml, source/puml/architecture/S-ENDA-production-container-diagram.puml
=> Issue289 production

source/architecture.rst, source/puml/architecture/S-ENDA-context-diagram.puml, source/puml/architecture/S-ENDA-data-distribution-container-diagram.puml, source/puml/architecture/S-ENDA-discovery-metadata-service-container-diagram.puml, source/puml/architecture/S-ENDA-monitoring-container-diagram.puml, source/puml/architecture/S-ENDA-production-container-diagram.puml, source/puml/architecture/obs-data-in-senda-context.puml
=> #294: updates according to recent changes
